#!/bin/bash
# curlt - curl with timing info

set -euo pipefail

FORMAT='code %{http_code}\n'
FORMAT+='size_header %{size_header}\n'
FORMAT+='size_download %{size_download}\n\n'
FORMAT+='namelookup %{time_namelookup}\n'
FORMAT+='connect %{time_connect}\n'
FORMAT+='appconnect %{time_appconnect}\n'
FORMAT+='time_pretransfer %{time_pretransfer}\n'
FORMAT+='starttransfer %{time_starttransfer}\n'
FORMAT+='total %{time_total}\n'

curl -L -so /dev/null -w "$FORMAT" "$1" | column -t
