local function map(mode, lhs, rhs, desc)
	vim.keymap.set(mode, lhs, rhs, { noremap = true, silent = true, desc = desc })
end

map("n", "<leader>qq", "<cmd>SmartQuit<CR>", "Smart quit current context")
map("t", "<leader>qq", "<C-\\><C-N><cmd>SmartQuit<CR>", "Smart quit terminal context")
map("n", "-", "<cmd>Oil<CR>", "Open Oil")
map("n", "<C-h>", "<C-w>h", "Move to window left")
map("n", "<C-j>", "<C-w>j", "Move to window below")
map("n", "<C-k>", "<C-w>k", "Move to window above")
map("n", "<C-l>", "<C-w>l", "Move to window right")
map("n", "<leader>fg", function()
	require("telescope.builtin").grep_string()
end, "Search word under cursor")
map("n", "<leader>fb", function()
	require("telescope.builtin").buffers()
end, "List open buffers")
map("n", "<leader>ff", function()
	require("telescope.builtin").find_files()
end, "Find files")
map("n", "<leader>v", "<cmd>vsplit<CR>", "Vertical split")
map("n", "<leader>h", "<cmd>split<CR>", "Horizontal split")
map("n", "<leader>w", "<cmd>SaveAll<CR>", "Write all buffers")
map("n", "<leader>g", "<cmd>LazyGit<CR>", "Open LazyGit")
map("n", "<leader>t", "<cmd>Floaterminal<CR>", "Toggle floating terminal")
map("n", "<leader>cc", function()
	local ok, client = pcall(require, "copilot.client")
	if ok and client.is_disabled() then
		vim.cmd("Copilot enable")
		return
	end

	vim.cmd("Copilot toggle")
end, "Toggle Copilot")
map("n", "<C-d>", "<C-d>zz", "Scroll down and center")
map("n", "<C-u>", "<C-u>zz", "Scroll up and center")
map("n", "<Esc>", "<cmd>nohlsearch<CR>", "Clear search highlights")
